### ISSUE TITLE
SSL Support

### ISSUE THREAD

**Issue by srikcgaa2** [RobHolme/HL7-Listener#1]
This is more a feature query.  Is there any work already done or plan to support SSL?

**Comment by srikcgaa2** [comment]
Or, is there a different fork where SSL is supported?

**Comment by RobHolme** [comment]
I've created a test release that adds TLS support - https://github.com/RobHolme/HL7-Listener/releases/tag/v1.4.dev 

I've done limited testing, so there are likely to be issues. If I get time I may add support to use server certificates from the windows cert store instead of relying on a pfx file - but not much spare time to spend on this at the moment.

Note: the -TLS parameter requires clients to connect via TLS, however any messages relayed via the -PassThru parameter will still be plain text only. 

As far as TLS support added to any forks - you'll need to take a look at the forks.
