### ISSUE TITLE
Unable To Create Connection To PassThru Host error

### ISSUE THREAD

**Issue by httpex** [RobHolme/HL7-Listener#5]
The error continues to say, "The operation is not allowed on non-connected sockets."

Is there a way to resolve this?

Thanks Rob!
Daniel

**Comment by RobHolme** [comment]
Really hard to even guess at the cause without any context of what conditions trigger the error, or a copy of the command line parameters, or any details on how the remote endpoint is configured. Googling the exception message you provided suggests the remote server has closed the TCP connection while the client was trying to write to the socket. I'd start investigating the settings for the remote HL7 endpoint - is it configured to close the socket connection after a period of inactivity - or after each message is received (instead of accepting multiple messages per connection).
